name: .NET Framework CI

# Für alle Push und Pull-Requests auf dem Branch main.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Die Aufgaben 
jobs:
  build:
    runs-on: windows-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Hier die gewünschte .NET Version angeben

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the solution
    - name: Build
      run: dotnet build --configuration Release

    # Run tests
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
