name: .NET Core CI333

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ./TESTneu2.sln

    - name: Build
      run: dotnet build ./TESTneu2.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test ./TESTneu2.sln --no-build --verbosity normal --configuration Release
