name: .NET CI22

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore LastTest2.sln

    # Build the solution
    - name: Build solution
      run: dotnet build LastTest2.sln --configuration Release --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test LastTest2.sln --configuration Release --no-build
